//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SauShelter.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Address
    {
        public Address()
        {
            this.Advert = new HashSet<Advert>();
            this.Insider = new HashSet<Insider>();
        }
    
        public System.Guid ID { get; set; }
        [Display(Name = "Açýklama")]
        public string EXPLANATION { get; set; }
        [Display(Name = "Þehir")]
        public Nullable<int> CITYID { get; set; }
        [Display(Name = "Ýlçe")]
        public Nullable<int> TOWNID { get; set; }
        [Display(Name = "Mahalle")]
        public Nullable<int> DISTRICTID { get; set; }
    
        public virtual ICollection<Advert> Advert { get; set; }
        public virtual ICollection<Insider> Insider { get; set; }
    }
}
