//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SauShelter.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class turkiyeEntities : DbContext
    {
        public turkiyeEntities()
            : base("name=turkiyeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_il> tbl_il { get; set; }
        public virtual DbSet<tbl_ilce> tbl_ilce { get; set; }
        public virtual DbSet<tbl_mahalle> tbl_mahalle { get; set; }
        public virtual DbSet<tbl_semt> tbl_semt { get; set; }
        public virtual DbSet<tbl_pk> tbl_pk { get; set; }
    }
}
