//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SauShelter.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Advert
    {
        public System.Guid ID { get; set; }
        [Display(Name="Ýlan Tarihi")]
        [Required]
        public System.DateTime ADVERTDATE { get; set; }
        [Display(Name = "Oda Sayýsý")]
        public Nullable<System.Guid> ROOMCOUNTID { get; set; }
        [Display(Name = "Bulunduðu Kat")]
        public Nullable<System.Guid> FLOORID { get; set; }
        [Display(Name = "Isýtma Sistemi")]
        public Nullable<System.Guid> HEATINGID { get; set; }
        [Display(Name = "Açýklama")]
        public string EXPLANATION { get; set; }
        [Display(Name = "Baþlýk")]
        [Required]
        public string TITLE { get; set; }
        [Display(Name = "Banyo Sayýsý")]
        public Nullable<int> BATHCOUNT { get; set; }
        [Display(Name = "Fiyatý")]
        [Required]
        public Nullable<int> COST { get; set; }
        [Display(Name = "Kaç Kiþilik")]
        public Nullable<int> PERSONCOUNT { get; set; }
        [Display(Name = "Ýlan Türü")]
        [Required]
        public System.Guid ATYPEID { get; set; }
        [Display(Name = "Balkon")]
        public Nullable<bool> BALCONY { get; set; }
        [Display(Name = "Bahçe")]
        public Nullable<bool> GARDEN { get; set; }
        [Display(Name = "Yapým Yýlý")]
        public Nullable<System.DateTime> CONSTRUCTIONDATE { get; set; }
        [Display(Name = "Adres")]
        public Nullable<System.Guid> ADDRESSID { get; set; }
        [Display(Name = "Aidat")]
        public Nullable<int> MONTHLYFEE { get; set; }
        [Display(Name = "Eþyalý")]
        public Nullable<bool> FULLYFURNISHED { get; set; }
        [Display(Name = "MetreKare")]
        public Nullable<int> SQUAREFEET { get; set; }
        [Display(Name = "Türü")]
        [Required]
        public System.Guid TYPID { get; set; }
        [Display(Name = "Ýlan Sahibi")]
        public System.Guid OWNERID { get; set; }
        [Display(Name = "Ýlan Süresi")]
        [Required]
        public Nullable<System.Guid> TIMEID { get; set; }
        [Display(Name = "Diðer")]
        public string OTHER { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual AdvertType AdvertType { get; set; }
        public virtual ApartmentFloor ApartmentFloor { get; set; }
        public virtual DeliveryTime DeliveryTime { get; set; }
        public virtual Heating Heating { get; set; }
        public virtual Insider Insider { get; set; }
        public virtual RoomCount RoomCount { get; set; }
        public virtual Type Type { get; set; }
    }
}
