//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SauShelter.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Insider
    {
        public Insider()
        {
            this.Advert = new HashSet<Advert>();
            this.OtherAdvert = new HashSet<OtherAdvert>();
        }
    
        public System.Guid ID { get; set; }
        [Display(Name = "Adý")]
        public string NAME { get; set; }
        [Display(Name = "E-Mail")]
        public string EMAIL { get; set; }
        [Display(Name = "Telefon Numarasý")]
        public string PHONENUMBER { get; set; }
        [Display(Name = "Þifre")]
        public string PASSWORD { get; set; }
        [Display(Name = "Doðum Tarihi")]
        public System.DateTime BIRTHDATE { get; set; }
        [Display(Name = "Cinsiyet")]
        public Nullable<bool> GENDER { get; set; }
        [Display(Name = "Adres")]
        public Nullable<System.Guid> ADDRESSID { get; set; }
        [Display(Name = "Soyadý")]
        public string SURNAME { get; set; }
        [Display(Name = "Þifre(Tekrar)")]
        public string CONFIRMPASSWORD { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual ICollection<Advert> Advert { get; set; }
        public virtual ICollection<OtherAdvert> OtherAdvert { get; set; }
    }
}
