//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SauShelter.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SauShelterEntities : DbContext
    {
        public SauShelterEntities()
            : base("name=SauShelterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Advert> Advert { get; set; }
        public virtual DbSet<AdvertType> AdvertType { get; set; }
        public virtual DbSet<ApartmentFloor> ApartmentFloor { get; set; }
        public virtual DbSet<DeliveryTime> DeliveryTime { get; set; }
        public virtual DbSet<Heating> Heating { get; set; }
        public virtual DbSet<Insider> Insider { get; set; }
        public virtual DbSet<OtherAdvert> OtherAdvert { get; set; }
        public virtual DbSet<OtherTypes> OtherTypes { get; set; }
        public virtual DbSet<RoomCount> RoomCount { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Type> Type { get; set; }
    }
}
